# https://aka.ms/yaml

name: "$(date:yyyyMMdd)$(rev:.r)"

trigger:
  - main

jobs:
  - job: PerfViewJS
    pool:
      vmImage: 'windows-2019'
      name: Azure Pipelines
      demands: msbuild

    steps:
    - task: MSBuild@1
      displayName: 'Build src/PerfViewJS.csproj'
      inputs:
        solution: src/PerfViewJS.csproj
        msbuildArguments: /restore
    - task: ComponentGovernanceComponentDetection@0
        inputs:
          scanType: 'Register'
          verbosity: 'Verbose'
          alertWarningLevel: 'High'